\documentclass{article}[12pt]
\usepackage{graphicx}
\usepackage{tabularx}
\usepackage{natbib}
\usepackage{gensymb}


\usepackage{array}
\usepackage{amsmath}
\usepackage{setspace}
%\usepackage[backend=bibtex]{biblatex}
\bibliographystyle{..//refs/styles/gcb.bst}

\setkeys{Gin}{width=0.8\textwidth}
%\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{10pt}
\setlength{\belowcaptionskip}{10pt}
\topmargin -1.5cm 
\oddsidemargin -0.04cm 
\evensidemargin -0.04cm 
\textwidth 16.59cm
\textheight 21.94cm 
\parskip 7.2pt 
\renewcommand{\baselinestretch}{1}
%\AtBeginEnvironment{thebibliography}{\linespread{1}\selectfont}
\parindent 0pt
\usepackage{lineno}
%\linenumbers % for dissertation


\begin{document}
\SweaveOpts{concordance=TRUE}
%\]\\bibliographystyle{..//..//sub_projs/refs/styles/scie.bst}
\def\labelitemi{--}
\parindent=24pt
%\noindent\includegraphics[width=0.2\textwidth]{logo.jpg}
\pagenumbering{gobble}
 
\\\\
\noindent{Dear Dr. Way,}

\noindent Please consider this manuscript ``Phenological sensitivity to climate change disrupts species coexistence" as a Research Report in \emph{Global Change Biology}.

\noindent\emph{1) What scientific question is addressed in this manuscript?}

\noindent Shifts in phenology---the seasonal timing of organisms' life cycle events---are one of the most widespread biological indicators of climate change, yet have often been overlooked in ecological theory and as a result, research to date has struggled to predict how species temporal interactions will shift with climate change. Here we present a simple, yet robust modeling framework to capture the dynamic interactions between the physical environment, phenology and coexistence.

\noindent\emph{2) What is/are the key finding(s) that answer this question?}

\noindent Here we show how modeling phenological differences as the realized product of an interaction between the environment (cues) and species physiologies links environmental change to competition. With this subtle, yet essential, adjustment we demonstrate how phenologically-mediated patterns of coexistence under historical climate conditions may degrade as climate warms.

\noindent \emph{3) Why is this work important and timely?}

\noindent Our manuscript provides a biologically realistic mechanism to project changes in these species interactions into the future, and a path forward for translating ecological theory into practice and advance a more predictive ecology that is better equipped to inform ecosystem conservation and management.
 
\noindent \emph{4) Describe how your paper fits within the scope of GCB.}

\noindent Our manuscript directly addresses the effects of global climate change on plant phenology and species interactions, a topic that is relevant in both natural and managed ecosystems around the world. 

\noindent \emph{5) What biological AND global change aspects does it address?}

\noindent Our paper addresses multiple aspects of biology including phenology, reproduction, resource acquisition and ecological dynamics in relation to global climate change.

\noindent \emph{6}) What are the three most recently published papers that are relevant to this manuscript?}

\noindent Three recent and relevant publications: \citet{Cleland2024, levine2022competition,Diez_2024}. See next page for full citation.

\noindent \emph{7) Provide the name and institutional email addresses of five potential reviewers.}
\begin{enumerate}
\item Dr. Meredith Zettlemoyer,meredith.zettlemoyer@umontana.edu
\item Dr. Mason Heberling, heberlingm@carnegiemnh.org
\item Dr. Guillaume Charrier, guillaune.charrier@inrae.fr
\item Dr. Jason Fridley, fridley@clemson.edu
\item Dr. Emily Grman, egrman@emich.edu
\end{enumerate}\\

\noindent We hope that you will find it suitable for publication in \textit{Global Change Biology}, and look forward to hearing from you.

\noindent Sincerely,\\


\noindent Daniel Buonaiuto
\newpage

\bibliography{prief_bibadd.bib}



\end{document}
