\documentclass{article}[12pt]
\usepackage{graphicx}
\usepackage{tabularx}
\usepackage{natbib}
\usepackage{gensymb}


\usepackage{array}
\usepackage{amsmath}
\usepackage{setspace}
%\usepackage[backend=bibtex]{biblatex}
\bibliographystyle{..//refs/styles/shortnat.bst}
\setkeys{Gin}{width=0.8\textwidth}
%\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{10pt}
\setlength{\belowcaptionskip}{10pt}
\topmargin -1.5cm 
\oddsidemargin -0.04cm 
\evensidemargin -0.04cm 
\textwidth 16.59cm
\textheight 21.94cm 
\parskip 7.2pt 
\renewcommand{\baselinestretch}{1.15}
%\AtBeginEnvironment{thebibliography}{\linespread{1}\selectfont}
\parindent 0pt
\usepackage{lineno}
%\linenumbers % for dissertation

\usepackage{xr-hyper}
\usepackage{hyperref}
%\usepackage{xr}
\externaldocument{supple}


\begin{document}
\SweaveOpts{concordance=TRUE}
%\]\\bibliographystyle{..//..//sub_projs/refs/styles/scie.bst}
\def\labelitemi{--}
\parindent=24pt
%\noindent\includegraphics[width=0.2\textwidth]{logo.jpg}
\pagenumbering{gobble}
\\\\
\noindent{Dear Dr. Wake,}

\noindent Please consider this manuscript ``Phenological sensitivity to climate change disrupts species coexistence" as a Brief Communication in \emph{Nature Climate Change}.


Shifts in phenology---the seasonal timing of organisms' life cycle events---are one of the most widespread biological indicators of climate change, yet the scale of these shifts varies substantially among species \citep{Zhang:2022aa,Roslin:2021aa}. These phenological differences among taxa have often been overlooked in ecological theory, but growing evidence suggests that they may play a major role in dictating community interactions and shaping the structure and function of ecological communities \citep{Cleland2024,Alexander:2019aa,volkerisaj}. With this, recent research has tried to integrate phenology into community assembly models, but current frameworks are not designed to capture the dynamic interactions between the physical environment, phenology and competition \citep{Loughnan:2024aa}. As a result, research to date has struggled to predict how species interactions will shift with climate change \citep{Urban:2016aa}.

To address this gap, we integrate empirical data on seed germination phenology with a well established community assembly models to show how modeling phenological differences  as the realized product of an interaction between the environment (cues) and species physiologies links environmental change to competition, provides a new framework to understand phenology within coexistence theory. With this subtle, yet essential, adjustment we demonstrate how phenologically-mediated patterns of coexistence under historical climate conditions may degrade as climate warms while providing a biologically realistic mechanism to project changes in these species iterations into the future. Our manuscript details a path forward to do this effectively and advance ecological theory, climate change biology, and the translational ecology that links them together.

We have previous discussed this manuscript with \emph{Nature Climate Change} Editor Dr. Tegan Armarego-Marriott on two occasions, first at during a recent meeting of Ecological Society of America meeting (Long Beach, California), and second though a prior submission as a Perspective Article. In our re-working of the manuscript to meet the criteria for a Brief Communication article, we cut subsection headers and condensed our main text, as well as updated our germination data analyses to make model findings more clear.

The main text of this manuscript is 1385 words in length and it contains two figures. It is co-authored by M.J. Donahue and E.M. Wolkovich and is not under consideration elsewhere. We hope that you will find it suitable for publication in \textit{Nature Climate Change}, and look forward to hearing from you.\\\
\\Sincerely,\\\\


\noindent Daniel Buonaiuto
\newpage
\bibliography{prief_bibadd.bib}


\end{document}
