
\documentclass{article}[12pt]
%Required: You must have these
\usepackage{graphicx}
\usepackage{tabularx}
\usepackage{natbib}
%\usepackage{caption}
%\usepackage{subcaption}
\usepackage{array}
\usepackage{amsmath}
%\usepackage[backend=bibtex]{biblatex}
\setkeys{Gin}{width=0.8\textwidth}
%\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{10pt}
\setlength{\belowcaptionskip}{10pt}
\topmargin -1.5cm 
\oddsidemargin -0.04cm 
\evensidemargin -0.04cm 
\textwidth 16.59cm
\textheight 23.94cm 
\parskip 7.2pt 
\renewcommand{\baselinestretch}{1.1} 	
\parindent 0pt

\bibliographystyle{refs/styles/newphyto.bst}
\begin{document}
\SweaveOpts{concordance=TRUE}

\section*{Introduction}
Each spring, in ecosystems across the temperate zone, ecological communities re-assemble form their period of winter dormancy with the hatching of insects, arrival of migratory birds, the germination of seeds and emergence of new leaves and flowers. The phenology---or seasonal timing---of these re-occurring life cycle events can be quite different, even among closely related organism in a shared habitat \citep{}. There is growing evidence that these phenological differences among taxa play a major role in dictating community interactions and shaping the structure and function of ecological communities \citep{}.

Phenological differences among species can generate seasonal priority effects; when earlier active species gain a competitive advantage by accesses limiting resources before their competitors emerge or arrive \citep{}. Recently the role of SPE's in coexistence has been demonstrated \citep{}(Say better). Basically, coexistence between stronger and weaker competitors can occur when phenological difference function as a stabilizing mechanisms; (i.e., weaker competitor because active first, thus reducing the competitive advantages of the stronger intrinsic competitor). These dynamics indicate there is an ecological tradeoff between phenology and competitive ability in the context of coexistence.

Yet mechanistically characterizing this tradeoff is challenge. This is because phenology is not a trait, but rather the realized product of an interaction between the environment (cues) and species unique physiology and genetic and developmental attributes. Environmental cues are changing rapidly, in fact phenological shifts are one of the most pronouced indicators of climate change. How ever species responses differ

\end{document}
